### ISSUE TITLE
Uncaught Exception in Operation Editor in dev.deepforge.org

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1725]
Navigating from `My Utilities` to `Operation Editor` and changing its color or adding attributes throws the following error in `dev.deepforge.org`. The code becomes unreachable and any operation cannot be executed even after refresh.  This behaviour also happens if there's any clipboard content pasted to the operation/ utilities code editor.

![image](https://user-images.githubusercontent.com/11476842/83885534-1ad78700-a70c-11ea-9608-3d4c3a5dd4a5.png)

![image](https://user-images.githubusercontent.com/11476842/83885588-2cb92a00-a70c-11ea-991a-c7b3d88b9d42.png)

**Comment by umesh-timalsina** [comment]
To be specific, in the server, the following error is thrown (if you refresh and try to execute the operation as is).

```
e:plugin:GenerateJob] Retrieving inputs and deserialize fns...
(node:1333) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getInputs' of undefined
    at GenerateJob.OperationOps.getInputs (/deepforge/src/common/plugin/Operation.js:32:36)
    at GenerateJob.createInputs (/deepforge/src/plugins/GenerateJob/GenerateJob.js:270:38)
    at GenerateJob.createOperationFiles (/deepforge/src/plugins/GenerateJob/GenerateJob.js:199:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GenerateJob.main (/deepforge/src/plugins/GenerateJob/GenerateJob.js:96:23)

```

**Comment by brollb** [comment]
From the stack trace, it appears that no operation is found in the operation's code. Can you share the value of `code` [here](https://github.com/deepforge-dev/deepforge/blob/master/src/common/viz/OperationControl.js#L215)?

**Comment by umesh-timalsina** [comment]
The value of the code there is as follows:

```py
import math

import numpy as np

from matplotlib import pyplot as plt
from astropy.visualization import make_lupton_rgb

from utils.data_utils import DataSetSampler


class VisualizeRandomGalaxies():
    def __init__(self, num_galaxies=10):
        self.num_galaxies = num_galaxies


    def execute(self):
        # Execute your operation here!
        sampler = DataSetSampler()
        num_galaxies = self.num_galaxies
        cols = 2
        rows = math.ceil(self.num_galaxies / cols)
        
        sample_indices = np.random.choice(sampler.tgt_indices, 
                                          size=num_galaxies,
                                          replace=False)
        
        img_arr = sampler.cube[sample_indices]
        labels_arr = sampler.labels[sample_indices]
        
        assert img_arr.shape = (num_galaxies, 64, 64, 5)
        
        for j in range(num_galaxies):
            print(f'Galaxy: {labels_arr[j]["imageID"]},'
                  f'Redshift: labels_arr[j]["z"]')
                  
        fig, axes = plt.subplots(rows, cols)
        count = 0
```

**Comment by brollb** [comment]
It is failing because there is a syntax error here:
```python
assert img_arr.shape = (num_galaxies, 64, 64, 5)
```
That said, it would be better for this to fail gracefully.

**Comment by brollb** [comment]
For example, a couple things that could be useful:
- requiring the user to fix this issues before execution
- integrate the code editor with a python language server or something similar
