### ISSUE TITLE
Failing tests on travis

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1839]
There are some failing tests on travis that should be resolved before the next release:
```
  1) Pipeline execution "before all" hook:
     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Pipeline execution "after all" hook:
     TypeError: Cannot read property 'kill' of undefined
      at Context.<anonymous> (test/integration/ExecutePipeline.spec.js:67:16)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by brollb** [comment]
After adding some debug logs, it looks like it is just an issue with the timeout being too low. It might also help to spin them up in parallel...
```
worker stdout is now: "2020-08-05T16:01:55.838Z ctor {
  metadata: {
    server: 'localhost',
    serverPort: '8080',
    httpsecure: false,
    logger: {
      debug: [Function: log],
      log: [Function: log],
      info: [Function: log],
      warn: [Function: log],
      error: [Function: err]
    },
    apiToken: undefined
  }
}
2020-08-05T16:01:55.842Z Running under node or node-web-kit
2020-08-05T16:01:55.846Z origin http://localhost:8080
2020-08-05T16:01:55.846Z blobUrl http://localhost:8080/rest/blob/
2020-08-05T16:01:55.846Z ctor {
  metadata: {
    server: 'localhost',
    serverPort: '8080',
    httpsecure: false,
    logger: {
      debug: [Function: log],
      log: [Function: log],
      info: [Function: log],
      warn: [Function: log],
      error: [Function: err]
    },
    apiToken: undefined
  }
}
2020-08-05T16:01:55.846Z Running under node
2020-08-05T16:01:55.847Z origin http://localhost:8080
2020-08-05T16:01:55.847Z executorUrl http://localhost:8080/rest/executor/
2020-08-05T16:01:55.847Z Connecting to http://localhost:8080
2020-08-05T16:01:55.913Z Connected to http://localhost:8080
```

**Comment by umesh-timalsina** [comment]
Is this the case for only worker compute being too slow to create conda env??

**Comment by brollb** [comment]
It should be unrelated since this is not actually running a job. (It is just trying to connect to the WebGME executor framework.)
