### ISSUE TITLE
Python Format Strings are not executed

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge#1901]
The following operation  
![image](https://user-images.githubusercontent.com/11476842/92654174-1398ba00-f2b5-11ea-8e69-60ec9cc04420.png)

Executes successfully. However the following fails

![image](https://user-images.githubusercontent.com/11476842/92654618-b5200b80-f2b5-11ea-86e2-682dbb775f84.png)

I suspect this is due to `skulpt` not recognizing format strings.

**Comment by umesh-timalsina** [comment]
The error message is:
```
TypeError: Cannot read property 'getInputs' of undefined
    at GenerateJob.OperationOps.getInputs (/home/umesh/work/deepforge-dev/deepforge/src/common/plugin/Operation.js:32:36)
    at GenerateJob.createInputs (/home/umesh/work/deepforge-dev/deepforge/src/plugins/GenerateJob/GenerateJob.js:270:38)
    at GenerateJob.createOperationFiles (/home/umesh/work/deepforge-dev/deepforge/src/plugins/GenerateJob/GenerateJob.js:199:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GenerateJob.main (/home/umesh/work/deepforge-dev/deepforge/src/plugins/GenerateJob/GenerateJob.js:96:23)

```

**Comment by brollb** [comment]
It might be worth considering switching skulpt out for a custom router providing the analysis for us as this would ensure we are using the correct python version (and wouldn't need to worry about discrepancies btwn skulpt and the python version used)...

**Comment by umesh-timalsina** [comment]
After #1908 a router might not be necessary, as a language server is capable of pointing out errors in code in the text editor iteself. This can get rid of skulpt.

**Comment by brollb** [comment]
Unfortunately, skulpt is not actually being used in the error here to provide LSP-like feedback to the editor. It is being used to determine the operation interface so it can keep the implementation and the interface editor in sync. Since it is a pretty specific task, it's not able to be replaced by a language server :/

Examples of it can be found in the tests [here](https://github.com/deepforge-dev/deepforge/blob/8ea9d65967539526077f7d5f61c4cd2da4ea9336/test/unit/common/OperationCode.spec.js).
