### ISSUE TITLE
Unable to execute interactive sessions on SciServer

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge#1927]
Interactive sessions have some additional dependencies not available by default on SciServer:
```
ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['node', 'start.js', 'http://localhost:8889', '0fba3d4d-d80c-5d36-8da9-d3524f4287b7']' command failed.  (See above for error)
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /home/idies/workspace/Temporary/brollb/scratch/execution-files/e59a1e2c5170b4b1e965549ec8d5051ec09b9196/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/idies/workspace/Temporary/brollb/scratch/execution-files/e59a1e2c5170b4b1e965549ec8d5051ec09b9196/start.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/idies/workspace/Temporary/brollb/scratch/execution-files/e59a1e2c5170b4b1e965549ec8d5051ec09b9196/start.js'
  ]
}

cp: cannot stat '/home/idies/workspace/Temporary/brollb/scratch/execution-files/e59a1e2c5170b4b1e965549ec8d5051ec09b9196/results.json': No such file or directory

```

**Comment by brollb** [comment]
(These should probably be added to the docker image on SciServer)

**Comment by brollb** [comment]
The docker image has been updated on SciServer so this is no longer an issue.
