### ISSUE TITLE
Hangup error when passing large file through remote worker

### ISSUE THREAD

**Issue by SeanNaren** [deepforge-dev/deepforge#997]
Getting the below error when passing a large file through a worker connected remotely (through our Nimbix worker) between nodes.

```
2017-03-23T00:19:27.349Z e10b83f1b8a42049333e8f82f723aa9f490b7a0f Failed to archive as "outputs/model" from "/home/nimbix/.deepforge/worker/worker_1490228329510/tmp/0/e10b83f1b8a42049333e8f82f723aa9f490b7a0f/outputs/model", err: Error: socket hang up
2017-03-23T00:19:27.349Z { Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketCloseListener (_http_client.js:284:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:492:12) code: 'ECONNRESET', response: undefined }
```

**Comment by brollb** [comment]
Thanks for the issue :) How big was the file again?

**Comment by SeanNaren** [comment]
400mb! Put it on s3 for you :)

**Comment by brollb** [comment]
this could be the fix: https://github.com/webgme/webgme/tree/master/config#server
